#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.16
# In conjunction with Tcl version 8.6
#    Sep 04, 2018 11:04:48 PM CDT  platform: Windows NT

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import agregar_persona_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    agregar_persona_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    agregar_persona_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font11 = "-family Arial -size 30 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font12 = "-family Arial -size 16 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font13 = "-family Arial -size 14 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font14 = "-family Arial -size 12 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font15 = "-family Arial -size 14 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        font9 = "-family Arial -size 20 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("700x400+954+370")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")



        self.btn_add = Button(top)
        self.btn_add.place(relx=0.84, rely=0.03, height=60, width=100)
        self.btn_add.configure(activebackground="#00e81f")
        self.btn_add.configure(activeforeground="#000000")
        self.btn_add.configure(background="#15af34")
        self.btn_add.configure(disabledforeground="#a3a3a3")
        self.btn_add.configure(font=font13)
        self.btn_add.configure(foreground="#000000")
        self.btn_add.configure(highlightbackground="#d9d9d9")
        self.btn_add.configure(highlightcolor="black")
        self.btn_add.configure(pady="0")
        self.btn_add.configure(state=DISABLED)
        self.btn_add.configure(text='''Agregar''')
        self.btn_add.configure(width=117)

        self.ent_name = Entry(top)
        self.ent_name.place(relx=0.2, rely=0.23,height=50, relwidth=0.23)
        self.ent_name.configure(background="white")
        self.ent_name.configure(disabledforeground="#a3a3a3")
        self.ent_name.configure(font=font15)
        self.ent_name.configure(foreground="#000000")
        self.ent_name.configure(insertbackground="black")
        self.ent_name.configure(width=144)

        self.ent_lastname = Entry(top)
        self.ent_lastname.place(relx=0.66, rely=0.23,height=50, relwidth=0.23)
        self.ent_lastname.configure(background="white")
        self.ent_lastname.configure(disabledforeground="#a3a3a3")
        self.ent_lastname.configure(font="TkFixedFont")
        self.ent_lastname.configure(foreground="#000000")
        self.ent_lastname.configure(insertbackground="black")
        self.ent_lastname.configure(width=164)

        self.lbl_name = Label(top)
        self.lbl_name.place(relx=0.01, rely=0.23, height=40, width=124)
        self.lbl_name.configure(background="#d9d9d9")
        self.lbl_name.configure(disabledforeground="#a3a3a3")
        self.lbl_name.configure(font=font9)
        self.lbl_name.configure(foreground="#000000")
        self.lbl_name.configure(text='''Nombre:''')
        self.lbl_name.configure(width=124)

        self.lbl_lastnames = Label(top)
        self.lbl_lastnames.place(relx=0.46, rely=0.23, height=40, width=134)
        self.lbl_lastnames.configure(background="#d9d9d9")
        self.lbl_lastnames.configure(disabledforeground="#a3a3a3")
        self.lbl_lastnames.configure(font=font9)
        self.lbl_lastnames.configure(foreground="#000000")
        self.lbl_lastnames.configure(text='''Apellidos:''')
        self.lbl_lastnames.configure(width=134)

        self.lbl_check_name = Label(top)
        self.lbl_check_name.place(relx=0.93, rely=0.25, height=32, width=32)
        self.lbl_check_name.configure(background="#d9d9d9")
        self.lbl_check_name.configure(disabledforeground="#a3a3a3")
        self.lbl_check_name.configure(foreground="#000000")
        self._img1 = PhotoImage(file="../../Proyectos/Python/RelojChecador/assets/error.png")
        self.lbl_check_name.configure(image=self._img1)
        self.lbl_check_name.configure(text='''x''')
        self.lbl_check_name.configure(width=54)

        self.lbl_title = Label(top)
        self.lbl_title.place(relx=0.01, rely=0.03, height=51, width=414)
        self.lbl_title.configure(background="#d9d9d9")
        self.lbl_title.configure(disabledforeground="#a3a3a3")
        self.lbl_title.configure(font=font11)
        self.lbl_title.configure(foreground="#000000")
        self.lbl_title.configure(text='''Creación de persona''')
        self.lbl_title.configure(width=414)

        self.lbl_finger = Label(top)
        self.lbl_finger.place(relx=0.01, rely=0.43, height=40, width=124)
        self.lbl_finger.configure(activebackground="#f9f9f9")
        self.lbl_finger.configure(activeforeground="black")
        self.lbl_finger.configure(background="#d9d9d9")
        self.lbl_finger.configure(disabledforeground="#a3a3a3")
        self.lbl_finger.configure(font=font9)
        self.lbl_finger.configure(foreground="#000000")
        self.lbl_finger.configure(highlightbackground="#d9d9d9")
        self.lbl_finger.configure(highlightcolor="black")
        self.lbl_finger.configure(text='''Huella:''')
        self.lbl_finger.configure(width=124)

        self.btn_finger1 = Button(top)
        self.btn_finger1.place(relx=0.2, rely=0.4, height=60, width=120)
        self.btn_finger1.configure(activebackground="#d9d9d9")
        self.btn_finger1.configure(activeforeground="#000000")
        self.btn_finger1.configure(background="#d9d9d9")
        self.btn_finger1.configure(disabledforeground="#a3a3a3")
        self.btn_finger1.configure(font=font12)
        self.btn_finger1.configure(foreground="#000000")
        self.btn_finger1.configure(highlightbackground="#d9d9d9")
        self.btn_finger1.configure(highlightcolor="black")
        self.btn_finger1.configure(pady="0")
        self.btn_finger1.configure(text='''#1''')
        self.btn_finger1.configure(width=117)

        self.btn_finger2 = Button(top)
        self.btn_finger2.place(relx=0.49, rely=0.4, height=60, width=120)
        self.btn_finger2.configure(activebackground="#d9d9d9")
        self.btn_finger2.configure(activeforeground="#000000")
        self.btn_finger2.configure(background="#d9d9d9")
        self.btn_finger2.configure(disabledforeground="#a3a3a3")
        self.btn_finger2.configure(font=font12)
        self.btn_finger2.configure(foreground="#000000")
        self.btn_finger2.configure(highlightbackground="#d9d9d9")
        self.btn_finger2.configure(highlightcolor="black")
        self.btn_finger2.configure(pady="0")
        self.btn_finger2.configure(text='''#2''')
        self.btn_finger2.configure(width=117)

        self.lbl_check1 = Label(top)
        self.lbl_check1.place(relx=0.4, rely=0.43, height=32, width=32)
        self.lbl_check1.configure(activebackground="#f9f9f9")
        self.lbl_check1.configure(activeforeground="black")
        self.lbl_check1.configure(background="#d9d9d9")
        self.lbl_check1.configure(disabledforeground="#a3a3a3")
        self.lbl_check1.configure(foreground="#000000")
        self.lbl_check1.configure(highlightbackground="#d9d9d9")
        self.lbl_check1.configure(highlightcolor="black")
        self._img2 = PhotoImage(file="../../Proyectos/Python/RelojChecador/assets/error.png")
        self.lbl_check1.configure(image=self._img2)
        self.lbl_check1.configure(text='''x''')

        self.lbl_check2 = Label(top)
        self.lbl_check2.place(relx=0.69, rely=0.43, height=32, width=32)
        self.lbl_check2.configure(activebackground="#f9f9f9")
        self.lbl_check2.configure(activeforeground="black")
        self.lbl_check2.configure(background="#d9d9d9")
        self.lbl_check2.configure(disabledforeground="#a3a3a3")
        self.lbl_check2.configure(foreground="#000000")
        self.lbl_check2.configure(highlightbackground="#d9d9d9")
        self.lbl_check2.configure(highlightcolor="black")
        self._img3 = PhotoImage(file="../../Proyectos/Python/RelojChecador/assets/error.png")
        self.lbl_check2.configure(image=self._img3)
        self.lbl_check2.configure(text='''x''')

        self.lbl_status = Label(top)
        self.lbl_status.place(relx=0.74, rely=0.4, height=61, width=174)
        self.lbl_status.configure(background="#d9d9d9")
        self.lbl_status.configure(disabledforeground="#a3a3a3")
        self.lbl_status.configure(font=font13)
        self.lbl_status.configure(foreground="#e80000")
        self.lbl_status.configure(text='''Levanta el dedo''')
        self.lbl_status.configure(width=174)

        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.01, rely=0.6, relheight=0.39, relwidth=0.98)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=685)

        self.btn_kQ = Button(self.Frame1)
        self.btn_kQ.place(relx=0.01, rely=0.06, height=40, width=40)
        self.btn_kQ.configure(activebackground="#d9d9d9")
        self.btn_kQ.configure(activeforeground="#000000")
        self.btn_kQ.configure(background="#d9d9d9")
        self.btn_kQ.configure(disabledforeground="#a3a3a3")
        self.btn_kQ.configure(font=font14)
        self.btn_kQ.configure(foreground="#000000")
        self.btn_kQ.configure(highlightbackground="#d9d9d9")
        self.btn_kQ.configure(highlightcolor="black")
        self.btn_kQ.configure(pady="0")
        self.btn_kQ.configure(text='''Q''')
        self.btn_kQ.configure(width=37)

        self.btn_kA = Button(self.Frame1)
        self.btn_kA.place(relx=0.01, rely=0.39, height=40, width=40)
        self.btn_kA.configure(activebackground="#d9d9d9")
        self.btn_kA.configure(activeforeground="#000000")
        self.btn_kA.configure(background="#d9d9d9")
        self.btn_kA.configure(disabledforeground="#a3a3a3")
        self.btn_kA.configure(font=font14)
        self.btn_kA.configure(foreground="#000000")
        self.btn_kA.configure(highlightbackground="#d9d9d9")
        self.btn_kA.configure(highlightcolor="black")
        self.btn_kA.configure(pady="0")
        self.btn_kA.configure(text='''A''')
        self.btn_kA.configure(width=37)

        self.btn_kZ = Button(self.Frame1)
        self.btn_kZ.place(relx=0.01, rely=0.71, height=40, width=40)
        self.btn_kZ.configure(activebackground="#d9d9d9")
        self.btn_kZ.configure(activeforeground="#000000")
        self.btn_kZ.configure(background="#d9d9d9")
        self.btn_kZ.configure(disabledforeground="#a3a3a3")
        self.btn_kZ.configure(font=font14)
        self.btn_kZ.configure(foreground="#000000")
        self.btn_kZ.configure(highlightbackground="#d9d9d9")
        self.btn_kZ.configure(highlightcolor="black")
        self.btn_kZ.configure(pady="0")
        self.btn_kZ.configure(text='''Z''')
        self.btn_kZ.configure(width=37)

        self.btn_kW = Button(self.Frame1)
        self.btn_kW.place(relx=0.09, rely=0.06, height=40, width=40)
        self.btn_kW.configure(activebackground="#d9d9d9")
        self.btn_kW.configure(activeforeground="#000000")
        self.btn_kW.configure(background="#d9d9d9")
        self.btn_kW.configure(disabledforeground="#a3a3a3")
        self.btn_kW.configure(font=font14)
        self.btn_kW.configure(foreground="#000000")
        self.btn_kW.configure(highlightbackground="#d9d9d9")
        self.btn_kW.configure(highlightcolor="black")
        self.btn_kW.configure(pady="0")
        self.btn_kW.configure(text='''W''')






if __name__ == '__main__':
    vp_start_gui()


