#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.16
# In conjunction with Tcl version 8.6
#    Sep 03, 2018 06:00:23 AM CDT  platform: Windows NT

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import pin_page_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    pin_page_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    pin_page_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font10 = "-family Arial -size 20 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font9 = "-family Arial -size 40 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("700x400+864+402")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=585)

        self.btn_back = Button(self.Frame1)
        self.btn_back.place(relx=0.01, rely=0.03, height=78, width=78)
        self.btn_back.configure(activebackground="#d9d9d9")
        self.btn_back.configure(activeforeground="#000000")
        self.btn_back.configure(background="#d9d9d9")
        self.btn_back.configure(disabledforeground="#a3a3a3")
        self.btn_back.configure(foreground="#000000")
        self.btn_back.configure(highlightbackground="#d9d9d9")
        self.btn_back.configure(highlightcolor="black")
        self._img1 = PhotoImage(file="../Proyectos/Python/RelojChecador/assets/arrow.png")
        self.btn_back.configure(image=self._img1)
        self.btn_back.configure(pady="0")
        self.btn_back.configure(text='''Button''')

        self.lbl_pin = Label(self.Frame1)
        self.lbl_pin.place(relx=0.27, rely=0.08, height=91, width=314)
        self.lbl_pin.configure(activebackground="#f9f9f9")
        self.lbl_pin.configure(activeforeground="black")
        self.lbl_pin.configure(background="#d9d9d9")
        self.lbl_pin.configure(disabledforeground="#a3a3a3")
        self.lbl_pin.configure(font=font9)
        self.lbl_pin.configure(foreground="#000000")
        self.lbl_pin.configure(highlightbackground="#d9d9d9")
        self.lbl_pin.configure(highlightcolor="black")
        self.lbl_pin.configure(text='''8888''')

        self.frame_keypad = Frame(self.Frame1)
        self.frame_keypad.place(relx=0.03, rely=0.4, relheight=0.56
                , relwidth=0.95)
        self.frame_keypad.configure(relief=GROOVE)
        self.frame_keypad.configure(borderwidth="2")
        self.frame_keypad.configure(relief=GROOVE)
        self.frame_keypad.configure(background="#d9d9d9")
        self.frame_keypad.configure(highlightbackground="#d9d9d9")
        self.frame_keypad.configure(highlightcolor="black")
        self.frame_keypad.configure(width=665)

        self.btn_1 = Button(self.frame_keypad)
        self.btn_1.place(relx=0.02, rely=0.04, height=90, width=90)
        self.btn_1.configure(activebackground="#d9d9d9")
        self.btn_1.configure(activeforeground="#000000")
        self.btn_1.configure(background="#d9d9d9")
        self.btn_1.configure(disabledforeground="#a3a3a3")
        self.btn_1.configure(font=font10)
        self.btn_1.configure(foreground="#000000")
        self.btn_1.configure(highlightbackground="#d9d9d9")
        self.btn_1.configure(highlightcolor="black")
        self.btn_1.configure(pady="0")
        self.btn_1.configure(text='''1''')

        self.btn_2 = Button(self.frame_keypad)
        self.btn_2.place(relx=0.18, rely=0.04, height=90, width=90)
        self.btn_2.configure(activebackground="#d9d9d9")
        self.btn_2.configure(activeforeground="#000000")
        self.btn_2.configure(background="#d9d9d9")
        self.btn_2.configure(disabledforeground="#a3a3a3")
        self.btn_2.configure(font=font10)
        self.btn_2.configure(foreground="#000000")
        self.btn_2.configure(highlightbackground="#d9d9d9")
        self.btn_2.configure(highlightcolor="black")
        self.btn_2.configure(pady="0")
        self.btn_2.configure(text='''2''')

        self.btn_3 = Button(self.frame_keypad)
        self.btn_3.place(relx=0.35, rely=0.04, height=90, width=90)
        self.btn_3.configure(activebackground="#d9d9d9")
        self.btn_3.configure(activeforeground="#000000")
        self.btn_3.configure(background="#d9d9d9")
        self.btn_3.configure(disabledforeground="#a3a3a3")
        self.btn_3.configure(font=font10)
        self.btn_3.configure(foreground="#000000")
        self.btn_3.configure(highlightbackground="#d9d9d9")
        self.btn_3.configure(highlightcolor="black")
        self.btn_3.configure(pady="0")
        self.btn_3.configure(text='''3''')

        self.btn_4 = Button(self.frame_keypad)
        self.btn_4.place(relx=0.51, rely=0.04, height=90, width=90)
        self.btn_4.configure(activebackground="#d9d9d9")
        self.btn_4.configure(activeforeground="#000000")
        self.btn_4.configure(background="#d9d9d9")
        self.btn_4.configure(disabledforeground="#a3a3a3")
        self.btn_4.configure(font=font10)
        self.btn_4.configure(foreground="#000000")
        self.btn_4.configure(highlightbackground="#d9d9d9")
        self.btn_4.configure(highlightcolor="black")
        self.btn_4.configure(pady="0")
        self.btn_4.configure(text='''4''')

        self.btn_5 = Button(self.frame_keypad)
        self.btn_5.place(relx=0.68, rely=0.04, height=90, width=90)
        self.btn_5.configure(activebackground="#d9d9d9")
        self.btn_5.configure(activeforeground="#000000")
        self.btn_5.configure(background="#d9d9d9")
        self.btn_5.configure(disabledforeground="#a3a3a3")
        self.btn_5.configure(font=font10)
        self.btn_5.configure(foreground="#000000")
        self.btn_5.configure(highlightbackground="#d9d9d9")
        self.btn_5.configure(highlightcolor="black")
        self.btn_5.configure(pady="0")
        self.btn_5.configure(text='''5''')

        self.btn_6 = Button(self.frame_keypad)
        self.btn_6.place(relx=0.02, rely=0.53, height=90, width=90)
        self.btn_6.configure(activebackground="#d9d9d9")
        self.btn_6.configure(activeforeground="#000000")
        self.btn_6.configure(background="#d9d9d9")
        self.btn_6.configure(disabledforeground="#a3a3a3")
        self.btn_6.configure(font=font10)
        self.btn_6.configure(foreground="#000000")
        self.btn_6.configure(highlightbackground="#d9d9d9")
        self.btn_6.configure(highlightcolor="black")
        self.btn_6.configure(pady="0")
        self.btn_6.configure(text='''6''')

        self.btn_7 = Button(self.frame_keypad)
        self.btn_7.place(relx=0.18, rely=0.53, height=90, width=90)
        self.btn_7.configure(activebackground="#d9d9d9")
        self.btn_7.configure(activeforeground="#000000")
        self.btn_7.configure(background="#d9d9d9")
        self.btn_7.configure(disabledforeground="#a3a3a3")
        self.btn_7.configure(font=font10)
        self.btn_7.configure(foreground="#000000")
        self.btn_7.configure(highlightbackground="#d9d9d9")
        self.btn_7.configure(highlightcolor="black")
        self.btn_7.configure(pady="0")
        self.btn_7.configure(text='''7''')

        self.btn_8 = Button(self.frame_keypad)
        self.btn_8.place(relx=0.35, rely=0.53, height=90, width=90)
        self.btn_8.configure(activebackground="#d9d9d9")
        self.btn_8.configure(activeforeground="#000000")
        self.btn_8.configure(background="#d9d9d9")
        self.btn_8.configure(disabledforeground="#a3a3a3")
        self.btn_8.configure(font=font10)
        self.btn_8.configure(foreground="#000000")
        self.btn_8.configure(highlightbackground="#d9d9d9")
        self.btn_8.configure(highlightcolor="black")
        self.btn_8.configure(pady="0")
        self.btn_8.configure(text='''8''')

        self.btn_9 = Button(self.frame_keypad)
        self.btn_9.place(relx=0.51, rely=0.53, height=90, width=90)
        self.btn_9.configure(activebackground="#d9d9d9")
        self.btn_9.configure(activeforeground="#000000")
        self.btn_9.configure(background="#d9d9d9")
        self.btn_9.configure(disabledforeground="#a3a3a3")
        self.btn_9.configure(font=font10)
        self.btn_9.configure(foreground="#000000")
        self.btn_9.configure(highlightbackground="#d9d9d9")
        self.btn_9.configure(highlightcolor="black")
        self.btn_9.configure(pady="0")
        self.btn_9.configure(text='''9''')

        self.btn_0 = Button(self.frame_keypad)
        self.btn_0.place(relx=0.68, rely=0.53, height=90, width=90)
        self.btn_0.configure(activebackground="#d9d9d9")
        self.btn_0.configure(activeforeground="#000000")
        self.btn_0.configure(background="#d9d9d9")
        self.btn_0.configure(disabledforeground="#a3a3a3")
        self.btn_0.configure(font=font10)
        self.btn_0.configure(foreground="#000000")
        self.btn_0.configure(highlightbackground="#d9d9d9")
        self.btn_0.configure(highlightcolor="black")
        self.btn_0.configure(pady="0")
        self.btn_0.configure(text='''0''')

        self.btn_del = Button(self.frame_keypad)
        self.btn_del.place(relx=0.84, rely=0.04, height=90, width=90)
        self.btn_del.configure(activebackground="#d9d9d9")
        self.btn_del.configure(activeforeground="#000000")
        self.btn_del.configure(background="#d82b2b")
        self.btn_del.configure(disabledforeground="#a3a3a3")
        self.btn_del.configure(font=font10)
        self.btn_del.configure(foreground="#000000")
        self.btn_del.configure(highlightbackground="#d9d9d9")
        self.btn_del.configure(highlightcolor="black")
        self.btn_del.configure(pady="0")
        self.btn_del.configure(text='''<<''')

        self.btn_enter = Button(self.frame_keypad)
        self.btn_enter.place(relx=0.84, rely=0.53, height=90, width=90)
        self.btn_enter.configure(activebackground="#d9d9d9")
        self.btn_enter.configure(activeforeground="#000000")
        self.btn_enter.configure(background="#18d865")
        self.btn_enter.configure(disabledforeground="#a3a3a3")
        self.btn_enter.configure(font=font10)
        self.btn_enter.configure(foreground="#000000")
        self.btn_enter.configure(highlightbackground="#d9d9d9")
        self.btn_enter.configure(highlightcolor="black")
        self.btn_enter.configure(pady="0")
        self.btn_enter.configure(text='''enter''')






if __name__ == '__main__':
    vp_start_gui()
